# Generated by Django 4.0.6 on 2023-06-17 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_set', to='goods.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.product')),
                ('clock', models.IntegerField(blank=True, null=True)),
                ('cores', models.IntegerField(blank=True, null=True)),
                ('tdp', models.IntegerField(blank=True, null=True)),
                ('architecture', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('goods.product', models.Model),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.product')),
                ('ramtype', models.CharField(blank=True, max_length=60, null=True)),
                ('ramwidth', models.IntegerField(blank=True, null=True)),
                ('ramclock', models.IntegerField(blank=True, null=True)),
                ('endmanufacturer', models.CharField(blank=True, max_length=60, null=True)),
                ('clock', models.IntegerField(blank=True, null=True)),
                ('tdp', models.IntegerField(blank=True, null=True)),
                ('architecture', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('goods.product', models.Model),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_see_items', 'Permission for salesmen'),),
            },
        ),
    ]
