# Generated by Django 4.0.6 on 2023-06-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_manufacturer_main_img_product_main_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='main_img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_img',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.product')),
            ],
        ),
    ]
